# https://github.com/mkhorasani/Streamlit-Authenticator
credentials:
  usernames:
    kildong:
      name: 홍길동
      password: 'xxx' # To be replaced with hashed password
cookie:
  expiry_days: 30  # 만료일 이라는데, 재인증 기능 필요없으면 0으로 세팅
  key: random_signature_key
  name: random_cookie_name